export default [
  { name: "Unicorn", department: "Co-founder at World Hope & Peace", photo: "https://i.imgur.com/8j0JUUQ.png" },
  { name: "Sean Conway", department: "Co-founder & CEO", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/sean_photo.png" },
  { name: "Justin M.", department: "Co-founder & President", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/justin_photo.png" },
  { name: "Dan P.", department: "Co-founder & Engineering", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/dan_photo.png" },
  { name: "Anthony A.", department: "Engineering", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/anthony_photo.png" },
  { name: "Chris B.", department: "Design", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/chris_photo.png" },
  { name: "Karly B.", department: "Product", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/karly_photo.png" },
  { name: "Melissa C.", department: "Engineering", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/melissa_photo.png" },
  { name: "Taylor D.", department: "Engineering", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/taylor_photo.png" },
  { name: "Christian E.", department: "Finance & Strategy", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/christian_photo.png" },
  { name: "Meg E.", department: "People Ops", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/meg_photo.png" },
  { name: "Mandy H.", department: "Client Care", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/mandy_photo.png" },
  { name: "Melissa H.", department: "Marketing", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/melissa_h_photo.png" },
  { name: "Nick H.", department: "Client Care", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/nick_photo.png" },
  { name: "Jason L.", department: "Product", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/jason_photo.png" },
  { name: "Anais P.", department: "Client Care", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/anais_photo.png" },
  { name: "Anna R.", department: "Client Care", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/anna_photo.png" },
  { name: "Charlie R.", department: "Sales", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/charlie_photo.png" },
  { name: "Monte T.", department: "Engineering", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/monte_photo.png" },
  { name: "Qianqian W.", department: "Design", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/qianqian_photo.png" },
  { name: "Luke X.", department: "Data Science", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/luke_photo.png" },
  { name: "Betty Y.", department: "Finance & Strategy", photo: "https://s3.amazonaws.com/pillow-assets/homepage_1/about+page/betty_photo.png" }
]
